"""Test helpers: render the contract's card, simulate an illuminant, encode JPEG.

Everything here is *ground truth*: the card is drawn from the same
``skintone.cards.definitions`` the server samples from, and the skin blocks are
filled with colours whose CIELAB (D65) value is known exactly before any camera
simulation is applied.

Colour spaces
-------------
* Rendered images are OpenCV ``BGR`` ``uint8`` (encoded sRGB) -- i.e. exactly what
  a camera JPEG would give this server.
* ``simulate_illuminant`` applies a **Bradford** adaptation from D65 to the scene
  illuminant in CIE XYZ, which is a linear map on linear sRGB. That is what makes
  the test meaningful: the server has to recover the D65 answer from data that has
  been pushed through a real chromatic-adaptation transform.
"""

from __future__ import annotations

import io

import cv2
import numpy as np
from numpy.typing import NDArray
from PIL import Image

from skintone import config
from skintone.cards import definitions
from skintone.color.adaptation import adaptation_matrix
from skintone.color.illuminant import daylight_xy
from skintone.color.srgb import (
    LINEAR_RGB_FROM_XYZ,
    XYZ_FROM_LINEAR_RGB,
    lab_to_linear_rgb,
    linear_to_srgb,
    srgb8_to_linear,
    white_xyz_from_xy,
)
BGR = NDArray[np.uint8]


def render_card() -> BGR:
    """Render ``skintone-a4-v1`` at its canonical 300 DPI rasterisation.

    Returns:
        ``(3508, 2480, 3)`` ``uint8`` BGR image: white paper, four real ArUco
        markers generated by OpenCV, and every patch filled with its nominal
        encoded sRGB value.
    """
    canvas = np.full((config.CARD_HEIGHT_PX, config.CARD_WIDTH_PX, 3), 255, dtype=np.uint8)
    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)

    for marker in definitions.MARKERS:
        # Only the black marker square carries the id; OpenCV generates the
        # NxN bit pattern including its mandatory black border.
        side = int(round(marker.size_mm * config.CARD_PX_PER_MM))
        marker_image = cv2.aruco.generateImageMarker(dictionary, marker.id, side)
        center_x = marker.center_mm[0] * config.CARD_PX_PER_MM
        center_y = marker.center_mm[1] * config.CARD_PX_PER_MM
        x0 = int(round(center_x - side / 2.0))
        y0 = int(round(center_y - side / 2.0))
        canvas[y0 : y0 + side, x0 : x0 + side] = cv2.cvtColor(marker_image, cv2.COLOR_GRAY2BGR)

    for patch in definitions.PATCHES:
        center_x, center_y = definitions.patch_center_px(patch)
        half = patch.size_mm * config.CARD_PX_PER_MM / 2.0
        x0 = int(round(center_x - half))
        y0 = int(round(center_y - half))
        x1 = int(round(center_x + half))
        y1 = int(round(center_y + half))
        colour = tuple(int(value) for value in reversed(patch.nominal_srgb))
        canvas[y0:y1, x0:x1] = colour
    return canvas


def render_scene(
    skin_labs: list[tuple[float, float, float]],
    *,
    card_scale: float = 0.75,
    perspective_px: float = 14.0,
) -> tuple[BGR, list[list[list[float]]], dict[str, object]]:
    """Build a full "photo": a perspective-warped card plus known-Lab skin blocks.

    Args:
        skin_labs: CIELAB (D65) values for the skin blocks; one block per entry.
        card_scale: Linear scale applied to the canonical card.
        perspective_px: Corner jitter that gives the homography real work to do.

    Returns:
        ``(scene_bgr, polygons, info)`` where ``polygons`` are original-image pixel
        polygons for ``rois.skin`` and ``info`` records the ground-truth Lab of each
        block together with the card's placement.
    """
    card = render_card()
    scaled_w = int(round(config.CARD_WIDTH_PX * card_scale))
    scaled_h = int(round(config.CARD_HEIGHT_PX * card_scale))
    card_scaled = cv2.resize(card, (scaled_w, scaled_h), interpolation=cv2.INTER_AREA)

    scene_w = scaled_w + 560
    scene_h = max(scaled_h + 160, 1200)
    scene = np.full((scene_h, scene_w, 3), 250, dtype=np.uint8)

    origin = (60, 80)
    source = np.array(
        [[0, 0], [scaled_w - 1, 0], [scaled_w - 1, scaled_h - 1], [0, scaled_h - 1]],
        dtype=np.float64,
    )
    target = np.array(
        [
            [origin[0] + perspective_px, origin[1]],
            [origin[0] + scaled_w - 1, origin[1] + perspective_px * 0.6],
            [origin[0] + scaled_w - 1 - perspective_px * 0.8, origin[1] + scaled_h - 1],
            [origin[0], origin[1] + scaled_h - 1 - perspective_px * 0.5],
        ],
        dtype=np.float64,
    )
    homography = cv2.getPerspectiveTransform(
        source.astype(np.float32), target.astype(np.float32)
    )
    warped = cv2.warpPerspective(
        card_scaled,
        homography,
        (scene_w, scene_h),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_TRANSPARENT,
    )
    mask = np.zeros((scene_h, scene_w), dtype=np.uint8)
    cv2.fillConvexPoly(mask, target.astype(np.int32), 255)
    scene[mask > 0] = warped[mask > 0]

    card_right = int(np.max(target[:, 0]))
    polygons: list[list[list[float]]] = []
    recorded: list[dict[str, object]] = []
    for index, lab in enumerate(skin_labs):
        x0 = card_right + 40
        x1 = min(x0 + 300, scene_w - 20)
        y0 = 160 + index * 460
        y1 = min(y0 + 380, scene_h - 20)
        linear = np.clip(lab_to_linear_rgb(np.asarray(lab, dtype=np.float64)), 0.0, 1.0)
        srgb8 = np.clip(np.round(linear_to_srgb(linear) * 255.0), 0, 255).astype(np.uint8)
        scene[y0:y1, x0:x1] = tuple(int(value) for value in reversed(srgb8))
        polygons.append(
            [
                [float(x0 + 20), float(y0 + 20)],
                [float(x1 - 20), float(y0 + 20)],
                [float(x1 - 20), float(y1 - 20)],
                [float(x0 + 20), float(y1 - 20)],
            ]
        )
        recorded.append({"lab": list(lab), "box": [x0, y0, x1, y1]})

    info: dict[str, object] = {
        "blocks": recorded,
        "cardScale": card_scale,
        "origin": list(origin),
        "size": [scene_w, scene_h],
    }
    return scene, polygons, info


def simulate_illuminant(
    image_bgr: BGR,
    illuminant_xy: tuple[float, float],
    *,
    exposure: float = 0.90,
    source_white: tuple[float, float] = (0.31271, 0.32902),
) -> BGR:
    """Push a D65-referred render through a known illuminant (Bradford).

    Args:
        image_bgr: ``(H, W, 3)`` encoded-sRGB image rendered as if under D65.
        illuminant_xy: Target scene illuminant chromaticity ``(x, y)``.
        exposure: Linear scene scale; keeps bright patches off the clip point.
        source_white: The white point the render is currently referenced to.

    Returns:
        ``(H, W, 3)`` ``uint8`` image: what a camera would see under
        ``illuminant_xy`` if it applied no white balance of its own.
    """
    linear = srgb8_to_linear(image_bgr[:, :, ::-1]).astype(np.float32)
    xyz = linear @ XYZ_FROM_LINEAR_RGB.T.astype(np.float32)
    matrix = adaptation_matrix(
        white_xyz_from_xy(source_white), white_xyz_from_xy(illuminant_xy), "Bradford"
    ).astype(np.float32)
    adapted = (xyz @ matrix.T) * np.float32(exposure)
    back = np.clip(adapted @ LINEAR_RGB_FROM_XYZ.T.astype(np.float32), 0.0, 1.0)
    srgb8 = np.clip(np.round(linear_to_srgb(back) * 255.0), 0, 255).astype(np.uint8)
    return np.ascontiguousarray(srgb8[:, :, ::-1])


def add_sensor_noise(image_bgr: BGR, sigma: float = 1.0, seed: int = 20260914) -> BGR:
    """Add reproducible Gaussian sensor noise in encoded sRGB units.

    Args:
        image_bgr: ``(H, W, 3)`` encoded-sRGB image.
        sigma: Standard deviation in 8-bit code values.
        seed: RNG seed, fixed so the test is deterministic.

    Returns:
        Noisy ``uint8`` image.
    """
    rng = np.random.default_rng(seed)
    noise = rng.normal(0.0, sigma, size=image_bgr.shape)
    noisy = np.clip(image_bgr.astype(np.float64) + noise, 0, 255).astype(np.uint8)
    return np.ascontiguousarray(noisy)


def encode_jpeg(image_bgr: BGR, quality: int = 92) -> bytes:
    """Encode an image as JPEG bytes, the way a phone would hand it to the API."""
    success, buffer = cv2.imencode(".jpg", image_bgr, [int(cv2.IMWRITE_JPEG_QUALITY), quality])
    if not success:  # pragma: no cover - imencode only fails on absurd input
        raise RuntimeError("JPEG encoding failed")
    return buffer.tobytes()


def encode_png(image_bgr: BGR) -> bytes:
    """Encode an image as lossless PNG bytes."""
    success, buffer = cv2.imencode(".png", image_bgr)
    if not success:  # pragma: no cover
        raise RuntimeError("PNG encoding failed")
    return buffer.tobytes()


def jpeg_with_exif(image_bgr: BGR, orientation: int = 6) -> bytes:
    """Encode a JPEG that carries an EXIF orientation tag and a stray comment.

    Used to prove the archive strips metadata while keeping orientation.

    Args:
        image_bgr: ``(H, W, 3)`` encoded-sRGB image.
        orientation: EXIF orientation value to embed.

    Returns:
        JPEG bytes with EXIF present.
    """
    rgb = Image.fromarray(image_bgr[:, :, ::-1])
    exif = Image.Exif()
    exif[274] = orientation
    exif[36867] = "2026:09:14 10:00:00"
    exif[270] = "secret description that must not survive archiving"
    buffer = io.BytesIO()
    rgb.save(buffer, format="JPEG", quality=95, exif=exif.tobytes())
    return buffer.getvalue()


def warm_illuminant_xy() -> tuple[float, float]:
    """Chromaticity of a realistic warm indoor-ish daylight (about 4200 K)."""
    xy = daylight_xy(4200.0)
    return float(xy[0]), float(xy[1])


def render_nocard_scene(
    skin_lab: tuple[float, float, float],
    *,
    width: int = 900,
    height: int = 1200,
    background_srgb: int = 188,
) -> tuple[BGR, list[list[list[float]]], dict[str, object]]:
    """Render a card-free "selfie" stand-in: a neutral background plus one skin block.

    The background fills the image border, which is where the no-card route looks
    for achromatic surfaces, so the illumination it should recover is exactly the
    one applied to the plain background.

    Args:
        skin_lab: CIELAB (D65) ground truth of the skin block.
        width: Scene width in pixels.
        height: Scene height in pixels.
        background_srgb: Encoded sRGB level of the neutral background.

    Returns:
        ``(scene_bgr, polygons, info)`` with ``polygons`` ready for ``rois.skin``.
    """
    scene = np.full((height, width, 3), background_srgb, dtype=np.uint8)
    x0, x1 = int(width * 0.30), int(width * 0.70)
    y0, y1 = int(height * 0.25), int(height * 0.75)
    linear = np.clip(lab_to_linear_rgb(np.asarray(skin_lab, dtype=np.float64)), 0.0, 1.0)
    srgb8 = np.clip(np.round(linear_to_srgb(linear) * 255.0), 0, 255).astype(np.uint8)
    scene[y0:y1, x0:x1] = tuple(int(value) for value in reversed(srgb8))
    polygon = [
        [float(x0 + 15), float(y0 + 15)],
        [float(x1 - 15), float(y0 + 15)],
        [float(x1 - 15), float(y1 - 15)],
        [float(x0 + 15), float(y1 - 15)],
    ]
    return scene, [polygon], {"lab": list(skin_lab), "box": [x0, y0, x1, y1]}
